## 학습목표
 1. numpy & pandas basic

* numpy 
  - 기본 array 생성

In [2]:
import numpy as np
print np.__version__

1.12.0


* ndarray
 - numpy의 기본 타입
 - vector, matrix를 표현
 - numpy.array([])로 생성

In [3]:
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 2], [2, 4, 6]])

print arr1, type(arr1)
print arr2, type(arr2)

[1 3 4 6] <type 'numpy.ndarray'>
[[0 1 2]
 [2 4 6]] <type 'numpy.ndarray'>


* arange 
 - range()와 동일한 기능을 수행함
 - ndarray 반환

In [7]:
arr3 = np.arange(1, 11)
print arr3, type(arr3)

[ 1  2  3  4  5  6  7  8  9 10] <type 'numpy.ndarray'>


 * linspace()            #리니어 스페이스
 - start, end를 n개의 균일한 간격으로 분할

In [4]:
# 0 - 2의 범위를 5-1 등분 한다는 이야기
arr4 = np.linspace(0, 2, 5)
arr5 = np.linspace(0, 2, 3)  #3등분
print arr4
print arr5

[ 0.   0.5  1.   1.5  2. ]
[ 0.  1.  2.]


* zeros
 - 전달된 tuple 사이즈 행렬 반환
 - 0으로 채워짐

In [15]:
print np.zeros((2, 4))  #2행 4열짜리 0 행렬을 만들어줌
print np.zeros(4)  #크기가 4인 벡터 생성

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[ 0.  0.  0.  0.]


* ones
 - 전달된 tuple 사이즈 행렬 반환
 - 1로 채워짐

In [4]:
print np.ones((3, 3, 2))  #3차원: 3행 2열을 3번만듬
print np.ones(3)

[[[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]]
[ 1.  1.  1.]


In [3]:
print np.random.rand(3) # [0, 1] 사이 출력
print np.random.randn(3) # normal:  정규분포(평균값 근처로 나옴)

[ 0.23701841  0.88209469  0.52287142]
[ 2.4681695   1.69280649  1.02542594]


In [25]:
np.random.seed(0) #랜덤한 값을 계속 유지하고 싶을 때 사용 : 숫자 값 1이라는 의미
print np.random.rand()

np.random.seed(1)
print np.random.rand()

np.random.seed(0)
print np.random.rand()

0.548813503927
0.417022004703
0.548813503927


* slicing
 - 리스트, 문자열 slicing과 동일함

In [27]:
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

In [62]:
print np.all(arr1>=0)
print (arr1>=0).all()

True
True


In [28]:
print arr1[0]
print arr1[1:-1]

1
[3 4]


In [8]:
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

print arr2[0]
print arr2[0, 1]
print arr2[1:, :2]  #1행부터~ /~2열까지 (2차원 유지)
print arr2[:, 2]  #2열만 가져옴 (1차원)
print arr2[:, 1:] #2차원


[0 1 3]
1
[[2 4]]
[3 6]
[[1 3]
 [4 6]]


* array masking
  - numpy의 원소를 선택하거나 제거하여 추출하는 방법

In [6]:
arr = np.random.randint(0, 35, 10)  #0~35사이(0포함,35포함X)에서 숫자 10개를 랜덤으로 가져오라
print arr

[24 34 19  6 34 31 20 23 25 31]


In [34]:
even_mask = (arr % 2 == 0)   #numpy 에서는 list에 연산을 하게 되면 각 원소마다 계산을 해줌!
print even_mask      #boolean타입으로 반환
print arr[even_mask]   #numpy에서는 이렇게 사용하면 true인것만 가져옴 


print arr[arr % 2 == 0]   #줄여서 이렇게 사용하기 
#filtering을 거는것을 mask라고 함

[ True False False  True False False False  True False  True]
[12 24  8 20]
[12 24  8 20]


* operations
  - 기본 연산은 벡터화되어 전체 원소에 적용된다.

In [35]:
arr = np.arange(1, 7) * 5
print arr

[ 5 10 15 20 25 30]


In [36]:
arr2 = arr ** 4
print arr2
print arr2 ** 0.5

[   625  10000  50625 160000 390625 810000]
[  25.  100.  225.  400.  625.  900.]


In [235]:
arr1 = np.arange(0, 30, 3) + 3
arr2 = np.arange(1, 11)
print arr1, arr2

print arr1 - arr2
print arr1 * arr2

[ 3  6  9 12 15 18 21 24 27 30] [ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[  3  12  27  48  75 108 147 192 243 300]


In [5]:
arr1 = np.array([[1, 1], [1, 1]])
arr2 = np.array([[2, 2], [2, 2]])

#(1,1) (2,2)
#(1,1) (2,2)
print arr1 * arr2  # 원소끼리의 곱
print arr1.dot(arr2) # 행렬 곱

[[2 2]
 [2 2]]
[[4 4]
 [4 4]]


* logical operator 
  - all(), any()

In [82]:
arr = np.random.randint(1, 10, size= (4,4))
print arr

[[7 6 4 8]
 [1 2 6 8]
 [6 5 3 7]
 [3 4 3 4]]


In [7]:
print np.all(arr < 11)  #조건을 다 만족하면 True, 한개라도 만족안하면 False

True


In [8]:
print np.any(arr % 7 == 0)  #한개라도 만족하면 참

True


* ravel
  - 다차원배열을 1차원으로 늘이기
  - 28 * 28 짜리 행렬 574 * 1 행렬로 바꿈
  - 비트맵 이미지 변환에 사용

In [9]:
arr = np.array([np.arange(1, 6), np.arange(10, 15)])
print arr
print arr.ravel()

[[ 1  2  3  4  5]
 [10 11 12 13 14]]
[ 1  2  3  4  5 10 11 12 13 14]


* reshaping
 - array의 shape을 재정렬

In [10]:
arr = np.arange(1, 16)
print arr
arr2 = arr.reshape(3, 5)
print arr2
print arr2.ravel()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


* 자주 쓰는 numpy 함수

In [13]:
print arr
print np.min(arr)
print np.mean(arr) #평균
print np.median(arr) #중간값
print np.max(arr)
print np.std(arr) #표준편차
print np.argmin(arr)  #최소값이 있는 인덱스 반환
print np.argmax(arr)
print np.sum(arr)
print np.sqrt(arr) #루트(각 값마다 구함)


A =  [[2, 3, 4], [1, 2, 3]]
B =  [[2, 3], [1, 2], [3, 4]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
8.0
8.0
15
4.32049379894
0
14
120

[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3.87298335]


* 연습문제)
1. numpy를 이용하여 Math.pi 값을 다시 구해봅시다.
2. python 기본 리스트 객체로 만든 두 행렬을 곱하는 코드를 작성하시오. (2x3) x(3x2)

In [14]:
import numpy as np

number =1000000
points =np.random.rand(number,2)
points_sum=np.sum(points ** 2, axis =1) #axis가 0이면 열별로 연산, axis가 1이면 행별로 연산
#points_sum = (points**2).sum(axis=1)
p= np.sum(points_sum <= 1.0)/float(number)
print p *4



3.141096


In [18]:
import numpy as np

arr1=np.array([[1,1,1],[1,1,1]])  #2x3
arr2=np.array([[2,2],[2,2],[2,2]])   #3x2

temp=[]
result = 0
if arr1.shape[1]==arr2.shape[0]:
    for i in range(arr1.shape[0]):  #2
        for j in range(arr2.shape[1]): #2
            for k in range(arr2.shape[0]):  #3
                result += arr1[i][k]* arr2[k][j]            
            temp.append(result)
            result = 0 

result_array= np.array(temp) 
print result_array.reshape(arr1.shape[0],arr2.shape[1])
print 
print arr1.dot(arr2)

[[6 6]
 [6 6]]

[[6 6]
 [6 6]]


* pandas basic
  - http://pandas.pydata.org/
  - Opensource python 고성능 데이터 분석 라이브러리
  - DataFrame, Series 객체가 가장 많이 사용
  - ML library인 scikit-learn과 함께 ML 분석에 많이 사용 됨
  - pip install pandas로 설치

In [10]:
import numpy as np
import pandas as pd

 * Series
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 인덱싱을 기능을 추가하여 1차원 배열을 나타냄
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성
  - 같은 타입의 0개 이상의 데이터를 가질 수 있음
  - 인덱스를 지정가능

In [21]:
s1 = pd.Series(20)
print s1  #64비트

0    20
dtype: int64


In [22]:
print s1[0]

20


In [23]:
s2 = pd.Series(range(1, 6))
print s2

0    1
1    2
2    3
3    4
4    5
dtype: int64


 * 값 및 인덱스 접근
  - 각가 values, index 속성

In [24]:
print s2.values

[1 2 3 4 5]


In [25]:
print s2.index

RangeIndex(start=0, stop=5, step=1)


* index 지정하기

In [26]:
s3 = pd.Series(range(1, 4), index = ['a', 'b', 'c'])
print s3
print
print s3.values
print
print s3.index

a    1
b    2
c    3
dtype: int64

[1 2 3]

Index([u'a', u'b', u'c'], dtype='object')


In [27]:
print s3[1] # 0base index 기본적으로 저장  #but 숫자로 index지정하게 되면 기본 0base 인덱스 사라짐
print s3['c'] 

2
3


* index 재사용

In [28]:
s4 = pd.Series(2, index = s3.index)
print s4

a    2
b    2
c    2
dtype: int64


In [29]:
s5 = pd.Series(np.random.randn(5))
print s5

0   -0.290593
1   -0.970117
2    1.217176
3    0.548642
4    0.378694
dtype: float64


In [30]:
s6 = pd.Series(np.arange(1, 9))
print s6

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int32


In [31]:
s7 = pd.Series({'a' : 100, 'b' : 1000, 'c' : 2, 'd' : 6})
print s7
print s7['b']
print s7[['a','b']]

a     100
b    1000
c       2
d       6
dtype: int64
1000
a     100
b    1000
dtype: int64


* Series size, shape, unique, count

In [32]:
s = pd.Series([0, 1, 1, 2, 3, 4, 5, 6, 7, np.nan]) #nan = not a number (값이 없음)
print s

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64


In [33]:
print len(s)

10


In [34]:
print s.size

10


In [35]:
print s.shape  #tuple로 반환

(10,)


In [36]:
print s.count() # NaN을 제외한 값을 카운팅

9


In [37]:
print s.unique()

[  0.   1.   2.   3.   4.   5.   6.   7.  nan]


In [38]:
print s.value_counts() # NaN 제외하고 값들을 카운팅 함   #많이씀!!!!!!

1.0    2
7.0    1
6.0    1
5.0    1
4.0    1
3.0    1
2.0    1
0.0    1
dtype: int64


* head, tail, take

In [39]:
s.head() # 상위 5개 출력
#s.head(3)# 상위 3개 출력

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
dtype: float64

In [40]:
s.head(n = 3)

0    0.0
1    1.0
2    1.0
dtype: float64

In [41]:
s.tail()

5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

In [42]:
s.tail(n = 2)

8    7.0
9    NaN
dtype: float64

In [43]:
print s
print 
print s.take([0, 4, 3, 9])  #해당되는 인덱스 가져옴

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

0    0.0
4    3.0
3    2.0
9    NaN
dtype: float64


In [70]:
s = pd.Series(np.arange(1, 4), index = ['x', 'y', 'z'])
s.take([0,2])
#s.take(['x', 'z']) #0 - based index만 가능

x    1
z    3
dtype: int32

* 값 접근하기

 * single value

In [68]:
print s['x']

1


In [69]:
print s[1]

2


* multiple values

In [72]:
print s 
print s[['x', 'z']]  #리스트를 가져옴
print s[[0,2]]

x    1
y    2
z    3
dtype: int32
x    1
z    3
dtype: int32
x    1
z    3
dtype: int32


In [12]:
s = pd.Series([1, 2, 3], index = [100, 101, 102])
print s

100    1
101    2
102    3
dtype: int64


* loc , iloc
  - loc[] : index
  - iloc[] : 0 based index

In [59]:
print s 
print
print s.loc[100]

100    1
101    2
102    3
dtype: int64

1


In [60]:
print s.iloc[0]

1


In [61]:
print s.loc[[100, 102]]

100    1
102    3
dtype: int64


In [62]:
print s.iloc[[0, 2]]

100    1
102    3
dtype: int64


In [63]:
s.loc[[100, 102, 104, 105]]  #없는것은 Nan출력

100    1.0
102    3.0
104    NaN
105    NaN
dtype: float64

In [64]:
s.iloc[[0, 2, 1]]

100    1
102    3
101    2
dtype: int64

* index를 기준으로 더하기

In [65]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print s1

a    1
b    2
c    3
d    4
dtype: int64


In [66]:
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s2

d    4
c    3
b    2
a    1
dtype: int64

In [67]:
print s1 + s2

a    2
b    4
c    6
d    8
dtype: int64


In [68]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])
a1 + a2

array([5, 5, 5, 5])

* 산술연산

In [195]:
print s1 ** 2  #각 원소마다 연산
print s1

a     1
b     4
c     9
d    16
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [281]:
exp = pd.Series(2, s1.index)
print s1 ** exp  #원소를 2승

a     1
b     4
c     9
d    16
dtype: int64


In [282]:
s1 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 5})
s2 = pd.Series({'b': 6, 'c': 7, 'd': 9, 'e': 10})

print s1 + s2

a     NaN
b     8.0
c    10.0
d    14.0
e     NaN
dtype: float64


 * NaN
  - numpy와 비교

In [74]:
nda = np.array([1, 2, 3, 4, 5])
nda.mean() #방법1
#np.mean(nda) #방법2

3.0

In [16]:
nda = np.array([1, 2, 3, 4, np.NaN])
nda.mean()

# numpy: 수학적 라이브러리 -> 없는것 nan출력 

nan

In [76]:
s = pd.Series([1, 2, 3, 4, np.NaN])
print s.mean()    # pandas: 데이터 분석 라이브러리-> 없는 것 skip하고 계산
print s.mean(skipna=False)  # skip하지않으려면 skipna=False

2.5
nan


 * **Boolean selection**
  - boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨

In [46]:
s = pd.Series(np.arange(1, 10))
s > 5

s[s>5]  #참인것만 출력하는 방법  (s>5를 masking으로)

5    6
6    7
7    8
8    9
dtype: int32

In [47]:
my_logic = s > 5
print s[my_logic]

5    6
6    7
7    8
8    9
dtype: int32


In [48]:
print s[s > 5]


5    6
6    7
7    8
8    9
dtype: int32


In [49]:
#print s > 5 and s < 8  #pandas, numpy에서 ->(X)에러
#print s[s > 5 and s < 8] #pandas, numpy에서 ->(X)에러
print s[(s > 5) & (s < 8)] # & and , | or

5    6
6    7
dtype: int32


In [52]:

print (s >= 0).all()
print (s >= 2).all()

True
False


In [289]:
print (s < 2).any()
print s[s < 2].any()

True
True


In [56]:
print s
print 
print s[s >= 7].sum()  #차이 이해하기
print (s >= 7).sum()
print
print (s >=7)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

24
3

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
dtype: bool


* Series 값 변경


In [290]:
s = pd.Series([1, 10, 100], index = ['a', 'b', 'c'])
s['d'] = 1000

print s

s['d'] = 10000
print s

a       1
b      10
c     100
d    1000
dtype: int64
a        1
b       10
c      100
d    10000
dtype: int64


In [291]:
del s['a']
print s

b       10
c      100
d    10000
dtype: int64


* Slicing

In [210]:
s = pd.Series(np.arange(100, 110), index=np.arange(10, 20))
print s 
print
print s[0:5]
print s[:5]
print s[5:]
print s[-3:]

10    100
11    101
12    102
13    103
14    104
15    105
16    106
17    107
18    108
19    109
dtype: int32

10    100
11    101
12    102
13    103
14    104
dtype: int32
10    100
11    101
12    102
13    103
14    104
dtype: int32
15    105
16    106
17    107
18    108
19    109
dtype: int32
17    107
18    108
19    109
dtype: int32


* DataFrame
  - Series가 1차원이라면 DataFrame은 2차원으로 확대된 버젼
  - Excel spreadsheet이라고 생각하면 이해하기 쉬움
  - 2차원이기 때문에 인덱스가 row, column로 구성됨

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame(np.array([[10, 11], [20, 22]]))
print df

    0   1
0  10  11
1  20  22


* shape

In [4]:
df1 = pd.DataFrame([pd.Series(np.arange(10, 15)) ,
            pd.Series(np.arange(20, 25))])
print df1
print df1.shape  #튜플로 행,열 갯수
print df1.info()
print df1.describe()   #data처음열면 head메소드와 함께 많이씀!!

    0   1   2   3   4
0  10  11  12  13  14
1  20  21  22  23  24
(2, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
0    2 non-null int32
1    2 non-null int32
2    2 non-null int32
3    2 non-null int32
4    2 non-null int32
dtypes: int32(5)
memory usage: 76.0 bytes
None
               0          1          2          3          4
count   2.000000   2.000000   2.000000   2.000000   2.000000
mean   15.000000  16.000000  17.000000  18.000000  19.000000
std     7.071068   7.071068   7.071068   7.071068   7.071068
min    10.000000  11.000000  12.000000  13.000000  14.000000
25%    12.500000  13.500000  14.500000  15.500000  16.500000
50%    15.000000  16.000000  17.000000  18.000000  19.000000
75%    17.500000  18.500000  19.500000  20.500000  21.500000
max    20.000000  21.000000  22.000000  23.000000  24.000000


In [78]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), columns = ['a', 'b'])
print df
print df.columns
print df.columns[0], df.columns[1]
print
df.columns = ['t1', 't2']
print df

    a   b
0  10  20
1  20  30
Index([u'a', u'b'], dtype='object')
a b

   t1  t2
0  10  20
1  20  30


In [75]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), columns = ['a', 'b'], index = ['d1', 'd2'])
print df
print df.index

     a   b
d1  10  20
d2  20  30
Index([u'd1', u'd2'], dtype='object')


* Series dictionary로 부터 생성

In [76]:
s1 = pd.Series(np.arange(1, 6, 1))
s2 = pd.Series(np.arange(6, 11, 1))
df = pd.DataFrame({'c1': s1, 'c2': s2})

print df

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10


In [7]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])  #usecols: 내가 원하는 컬럼만 긁어올수 있음
print sample_df.head()
print
print sample_df[['Price']].mean()
print
print sample_df[[2]].mean()

                       Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45
ATVI    Activision Blizzard  Information Technology   41.29       11.31

Price    86.044306
dtype: float64

Price    86.044306
dtype: float64


In [98]:
#0을 컬럼으로

In [80]:
#여기까지 했음

In [300]:
print len(sample_df)

504


In [81]:
print sample_df.index
print 
print sample_df.columns

Index([u'MMM', u'ABT', u'ABBV', u'ACN', u'ATVI', u'AYI', u'ADBE', u'AAP',
       u'AES', u'AET',
       ...
       u'XEL', u'XRX', u'XLNX', u'XL', u'XYL', u'YHOO', u'YUM', u'ZBH',
       u'ZION', u'ZTS'],
      dtype='object', name=u'Symbol', length=504)

Index([u'Name', u'Sector', u'Price', u'Book Value'], dtype='object')


In [17]:
#apple_df = pd.read_csv('apple.csv', header = None)  #컬럼명을 첫번째줄로 출력
apple_df = pd.read_csv('apple.csv')
print apple_df[:10]  #pandas 인덱싱 지원안함 [10]은 에러

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442
5  23-Sep-16  114.42  114.79  111.55  112.71  52481151
6  22-Sep-16  114.35  114.94  114.00  114.62  31073984
7  21-Sep-16  113.85  113.99  112.44  113.55  36003185
8  20-Sep-16  113.05  114.12  112.51  113.57  34514269
9  19-Sep-16  115.19  116.18  113.25  113.58  47023046


* column 선택하기

In [83]:
print apple_df[[0, 4, 5]]

         Date   Close     Volume
0   30-Sep-16  113.05   36379106
1   29-Sep-16  112.18   35886990
2   28-Sep-16  113.95   29641085
3   27-Sep-16  113.09   24607412
4   26-Sep-16  112.88   29869442
5   23-Sep-16  112.71   52481151
6   22-Sep-16  114.62   31073984
7   21-Sep-16  113.55   36003185
8   20-Sep-16  113.57   34514269
9   19-Sep-16  113.58   47023046
10  16-Sep-16  114.92   79886911
11  15-Sep-16  115.57   90613177
12  14-Sep-16  111.77  112340318
13  13-Sep-16  107.95   62176190
14  12-Sep-16  105.44   45292770
15   9-Sep-16  103.13   46556984
16   8-Sep-16  105.52   53002026
17   7-Sep-16  108.36   42364328
18   6-Sep-16  107.70   26880391
19   2-Sep-16  107.73   26334858
20   1-Sep-16  106.73   26701523


In [107]:
print type(apple_df[[0, 4, 5]])
print type(apple_df[[0]])
print type(apple_df[['Date']])
print type(apple_df[['Date', 'Close']])
print type(apple_df['Date'])  #결과를 Series로 반환

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [109]:
print apple_df.Date
print apple_df.Close

0     30-Sep-16
1     29-Sep-16
2     28-Sep-16
3     27-Sep-16
4     26-Sep-16
5     23-Sep-16
6     22-Sep-16
7     21-Sep-16
8     20-Sep-16
9     19-Sep-16
10    16-Sep-16
11    15-Sep-16
12    14-Sep-16
13    13-Sep-16
14    12-Sep-16
15     9-Sep-16
16     8-Sep-16
17     7-Sep-16
18     6-Sep-16
19     2-Sep-16
20     1-Sep-16
Name: Date, dtype: object
0     113.05
1     112.18
2     113.95
3     113.09
4     112.88
5     112.71
6     114.62
7     113.55
8     113.57
9     113.58
10    114.92
11    115.57
12    111.77
13    107.95
14    105.44
15    103.13
16    105.52
17    108.36
18    107.70
19    107.73
20    106.73
Name: Close, dtype: float64


* row 선택하기
  - Series의 경우 []로 row 선택이 가능하나, DataFrame의 경우는 기본적으로 column을 선택하도록 설계
  - [:10]과 같이 slicing의 경우에는 row 선택 가능
  - .loc, .iloc, .ix 의 함수로 row 선택 가능

In [42]:
print apple_df[:10]
print apple_df[[0,1]]
print apple_df[:10][[0,1]]
print apple_df['Date']
#print apple_df['Date','Open'] #->에러
#print apple_df[['Date','Open']]
#print apple_df[0] #->에러

        Date    Open    High     Low   Close    Volume
0  30-Sep-16  112.46  113.37  111.80  113.05  36379106
1  29-Sep-16  113.16  113.80  111.80  112.18  35886990
2  28-Sep-16  113.69  114.64  113.43  113.95  29641085
3  27-Sep-16  113.00  113.18  112.34  113.09  24607412
4  26-Sep-16  111.64  113.39  111.55  112.88  29869442
5  23-Sep-16  114.42  114.79  111.55  112.71  52481151
6  22-Sep-16  114.35  114.94  114.00  114.62  31073984
7  21-Sep-16  113.85  113.99  112.44  113.55  36003185
8  20-Sep-16  113.05  114.12  112.51  113.57  34514269
9  19-Sep-16  115.19  116.18  113.25  113.58  47023046
         Date    Open
0   30-Sep-16  112.46
1   29-Sep-16  113.16
2   28-Sep-16  113.69
3   27-Sep-16  113.00
4   26-Sep-16  111.64
5   23-Sep-16  114.42
6   22-Sep-16  114.35
7   21-Sep-16  113.85
8   20-Sep-16  113.05
9   19-Sep-16  115.19
10  16-Sep-16  115.12
11  15-Sep-16  113.86
12  14-Sep-16  108.73
13  13-Sep-16  107.51
14  12-Sep-16  102.65
15   9-Sep-16  104.64
16   8-Sep-16  107.25

In [165]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])
print sample_df['MMM' : 'ACN']  #'ACN'행까지 포함해서 출력
print
print sample_df [0:3]  #0에서 2행까지 출력

                       Name                  Sector   Price  Book Value
Symbol                                                                 
MMM              3M Company             Industrials  177.12       19.34
ABT     Abbott Laboratories             Health Care   41.89       14.10
ABBV                 AbbVie             Health Care   64.16        2.87
ACN           Accenture plc  Information Technology  115.11       11.45

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
ABBV                 AbbVie  Health Care   64.16        2.87


In [141]:
print sample_df.loc['MMM'] #Series로 반환

Name           3M Company
Sector        Industrials
Price              177.12
Book Value          19.34
Name: MMM, dtype: object


In [142]:
print sample_df.loc[['MMM', 'MSFT']]  #DataFrame으로 반환

                   Name                  Sector   Price  Book Value
Symbol                                                             
MMM          3M Company             Industrials  177.12       19.34
MSFT    Microsoft Corp.  Information Technology   52.30        9.51


In [123]:
print sample_df.iloc[[0, 1, 2]]
print type(sample_df.iloc[[0, 1, 2]])
print
print sample_df.iloc[0] 
print type(sample_df.iloc[0])

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
ABBV                 AbbVie  Health Care   64.16        2.87
<class 'pandas.core.frame.DataFrame'>

Name           3M Company
Sector        Industrials
Price              177.12
Book Value          19.34
Name: MMM, dtype: object
<class 'pandas.core.series.Series'>


In [124]:
print sample_df.ix[['MSFT', 'ZTS']]   #ix- 0base랑 문자열 다 받음

                   Name                  Sector  Price  Book Value
Symbol                                                            
MSFT    Microsoft Corp.  Information Technology   52.3        9.51
ZTS              Zoetis             Health Care   48.5        2.35


In [92]:
print sample_df.ix[[10, 11, 12, 15]]

                                 Name       Sector   Price  Book Value
Symbol                                                                
AMG     Affiliated Managers Group Inc   Financials  138.85       53.30
AFL                         AFLAC Inc   Financials   72.49       48.22
A            Agilent Technologies Inc  Health Care   45.48       12.79
ALK              Alaska Air Group Inc  Industrials   59.86       19.81


* boolean selection으로 row 선택하기

In [93]:
print sample_df.Price > 100

Symbol
MMM       True
ABT      False
ABBV     False
ACN       True
ATVI     False
AYI       True
ADBE     False
AAP       True
AES      False
AET       True
AMG       True
AFL      False
A        False
APD       True
AKAM     False
ALK      False
ALB      False
AA       False
ALXN      True
ALLE     False
AGN       True
ADS       True
LNT      False
ALL      False
GOOGL     True
GOOG      True
MO       False
AMZN      True
AEE      False
AAL      False
         ...  
V        False
VNO       True
VMC       True
WMT      False
WBA      False
WM       False
WAT       True
WFC      False
HCN      False
WDC      False
WU       False
WRK      False
WY       False
WHR       True
WFM      False
WMB      False
WLTW      True
WEC      False
WYN      False
WYNN     False
XEL      False
XRX      False
XLNX     False
XL       False
XYL      False
YHOO     False
YUM      False
ZBH       True
ZION     False
ZTS      False
Name: Price, dtype: bool


In [144]:
print sample_df[sample_df.Price > 100][['Price','Name']]

         Price                                  Name
Symbol                                              
MMM     177.12                            3M Company
ACN     115.11                         Accenture plc
AYI     264.62                     Acuity Brands Inc
AAP     164.85                    Advance Auto Parts
AET     117.00                             Aetna Inc
AMG     138.85         Affiliated Managers Group Inc
APD     144.35          Air Products & Chemicals Inc
ALXN    124.42               Alexion Pharmaceuticals
AGN     240.59                          Allergan plc
ADS     200.96                 Alliance Data Systems
GOOGL   717.78                  Alphabet Inc Class A
GOOG    705.63                  Alphabet Inc Class C
AMZN    745.81                        Amazon.com Inc
AMT     113.66                 American Tower Corp A
AMGN    161.10                             Amgen Inc
ANTM    132.15                           Anthem Inc.
AON     109.57                               A

* 새 column 추가하기

In [180]:
copy = sample_df.copy()  #중요
copy['TwicePrice'] = sample_df.Price * 2  #맨뒤에 입력됨
print copy[:10]

                       Name                  Sector   Price  Book Value  \
Symbol                                                                    
MMM              3M Company             Industrials  177.12       19.34   
ABT     Abbott Laboratories             Health Care   41.89       14.10   
ABBV                 AbbVie             Health Care   64.16        2.87   
ACN           Accenture plc  Information Technology  115.11       11.45   
ATVI    Activision Blizzard  Information Technology   41.29       11.31   
AYI       Acuity Brands Inc             Industrials  264.62       36.50   
ADBE      Adobe Systems Inc  Information Technology   96.79       14.53   
AAP      Advance Auto Parts  Consumer Discretionary  164.85       35.82   
AES                AES Corp               Utilities   12.32        4.86   
AET               Aetna Inc             Health Care  117.00       47.96   

        TwicePrice  
Symbol              
MMM         354.24  
ABT          83.78  
ABBV        128

In [181]:
copy.insert(1, 'TriplePrice', sample_df.Price * 3)  #1의 위치에 TriplePrice 열 입력
print copy[:2]

                       Name  TriplePrice       Sector   Price  Book Value  \
Symbol                                                                      
MMM              3M Company       531.36  Industrials  177.12       19.34   
ABT     Abbott Laboratories       125.67  Health Care   41.89       14.10   

        TwicePrice  
Symbol              
MMM         354.24  
ABT          83.78  


 * column 삭제하기

In [43]:
print copy[:2]

del copy['Sector']

print copy[:2]

NameError: name 'copy' is not defined

In [183]:
copy.tail()

Name  TriplePrice   Price  Book Value  TwicePrice
Symbol                                                                     
YHOO                Yahoo Inc.       113.22   37.74       30.03       75.48
YUM            Yum! Brands Inc       257.28   85.76        0.38      171.52
ZBH     Zimmer Biomet Holdings       374.67  124.89       48.52      249.78
ZION             Zions Bancorp        74.22   24.74       33.23       49.48
ZTS                     Zoetis       145.50   48.50        2.35       97.00

 * row 추가/삭제하기

In [184]:
df1 = copy.iloc[0:3].copy()
print df1
copy = copy.append(df1)  #맨뒤에 행추가
copy.tail()

copy.loc['Aaron'] = ['Aaron', 1000.0, 1000.0, 1000.0, 2000.0]
copy.tail()

                       Name  TriplePrice   Price  Book Value  TwicePrice
Symbol                                                                  
MMM              3M Company       531.36  177.12       19.34      354.24
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78
ABBV                 AbbVie       192.48   64.16        2.87      128.32


Name  TriplePrice    Price  Book Value  TwicePrice
Symbol                                                                   
ZTS                  Zoetis       145.50    48.50        2.35       97.00
MMM              3M Company       531.36   177.12       19.34      354.24
ABT     Abbott Laboratories       125.67    41.89       14.10       83.78
ABBV                 AbbVie       192.48    64.16        2.87      128.32
Aaron                 Aaron      1000.00  1000.00     1000.00     2000.00

In [185]:
copy = copy.drop(['Aaron'])   #row 지우는것
copy.tail()

Name  TriplePrice   Price  Book Value  TwicePrice
Symbol                                                                  
ZION          Zions Bancorp        74.22   24.74       33.23       49.48
ZTS                  Zoetis       145.50   48.50        2.35       97.00
MMM              3M Company       531.36  177.12       19.34      354.24
ABT     Abbott Laboratories       125.67   41.89       14.10       83.78
ABBV                 AbbVie       192.48   64.16        2.87      128.32

In [27]:
selection = sample_df.Price > 200
lessthan200 = sample_df[-selection]   #-표시 ->반전시킴: 200이하인것 표시
print lessthan200[:2]

morethan200 = sample_df[selection]
print morethan200[:3]

                       Name       Sector   Price  Book Value
Symbol                                                      
MMM              3M Company  Industrials  177.12       19.34
ABT     Abbott Laboratories  Health Care   41.89       14.10
                         Name                  Sector   Price  Book Value
Symbol                                                                   
AYI         Acuity Brands Inc             Industrials  264.62       36.50
AGN              Allergan plc             Health Care  240.59      183.41
ADS     Alliance Data Systems  Information Technology  200.96       29.51
